// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: brewtrack.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "brewtrack.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* Brewtrack_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Brewtrack_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_brewtrack_2eproto() {
  protobuf_AddDesc_brewtrack_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "brewtrack.proto");
  GOOGLE_CHECK(file != NULL);
  Brewtrack_descriptor_ = file->message_type(0);
  static const int Brewtrack_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Brewtrack, id_),
  };
  Brewtrack_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Brewtrack_descriptor_,
      Brewtrack::default_instance_,
      Brewtrack_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Brewtrack, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Brewtrack, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Brewtrack));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_brewtrack_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Brewtrack_descriptor_, &Brewtrack::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_brewtrack_2eproto() {
  delete Brewtrack::default_instance_;
  delete Brewtrack_reflection_;
}

void protobuf_AddDesc_brewtrack_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::protobuf_AddDesc_uuid_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\017brewtrack.proto\032\nuuid.proto\"\036\n\tBrewtra"
    "ck\022\021\n\002id\030\001 \001(\0132\005.uuid", 61);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "brewtrack.proto", &protobuf_RegisterTypes);
  Brewtrack::default_instance_ = new Brewtrack();
  Brewtrack::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_brewtrack_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_brewtrack_2eproto {
  StaticDescriptorInitializer_brewtrack_2eproto() {
    protobuf_AddDesc_brewtrack_2eproto();
  }
} static_descriptor_initializer_brewtrack_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int Brewtrack::kIdFieldNumber;
#endif  // !_MSC_VER

Brewtrack::Brewtrack()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Brewtrack::InitAsDefaultInstance() {
  id_ = const_cast< ::uuid*>(&::uuid::default_instance());
}

Brewtrack::Brewtrack(const Brewtrack& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Brewtrack::SharedCtor() {
  _cached_size_ = 0;
  id_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Brewtrack::~Brewtrack() {
  SharedDtor();
}

void Brewtrack::SharedDtor() {
  if (this != default_instance_) {
    delete id_;
  }
}

void Brewtrack::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Brewtrack::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Brewtrack_descriptor_;
}

const Brewtrack& Brewtrack::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_brewtrack_2eproto();
  return *default_instance_;
}

Brewtrack* Brewtrack::default_instance_ = NULL;

Brewtrack* Brewtrack::New() const {
  return new Brewtrack;
}

void Brewtrack::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_id()) {
      if (id_ != NULL) id_->::uuid::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Brewtrack::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .uuid id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_id()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Brewtrack::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional .uuid id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->id(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Brewtrack::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional .uuid id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->id(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Brewtrack::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .uuid id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->id());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Brewtrack::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Brewtrack* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Brewtrack*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Brewtrack::MergeFrom(const Brewtrack& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      mutable_id()->::uuid::MergeFrom(from.id());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Brewtrack::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Brewtrack::CopyFrom(const Brewtrack& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Brewtrack::IsInitialized() const {

  if (has_id()) {
    if (!this->id().IsInitialized()) return false;
  }
  return true;
}

void Brewtrack::Swap(Brewtrack* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Brewtrack::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Brewtrack_descriptor_;
  metadata.reflection = Brewtrack_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
